name: Angular

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configuration de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 26
        cache: 'npm' 


    - name: Installation des dépendances
      run: npm ci

    - name: Audit et Correction des vulnérabilités
      run: npm audit fix 


    - name: Vérification de la compilation 
      run: npm run build -- --configuration=production


    - name: Exécution des tests unitaires
      run: npm run test:ci