name: Angular CI (Frontend TDD)

# Déclencheurs : Le workflow s'exécute à chaque push ou pull request sur la branche principale
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configuration de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm' 


    - name: Installation des dépendances
      run: npm ci


    - name: Vérification de la compilation (Build)
      run: npm run build -- --configuration=production


    - name: Exécution des tests unitaires
      run: npm run test:ci